services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peluq_app
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - DB_HOST=${DB_HOST}  # Usar el host online
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint: /bin/sh -c "if [ ! -d /var/www/.git ]; then git clone ${GIT_REPO_URL} /var/www; fi && apache2-foreground"
